version: "2"
services:
  apache17:
    build:
      context: images/php
      dockerfile: Dockerfile-php7.3
      args:
        username: ${USERNAME}
    container_name: ${APPLICATION}17_apachephp
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ${HOST_PS17_PATH}:/var/www/html:cached
      - ${PLUGIN_PATH}/:/var/www/html/modules/${PLUGIN_NAME}/
    networks:
      - mynetwork

  apache16:
    build:
      context: images/php
      dockerfile: Dockerfile-php7.1
      args:
        username: ${USERNAME}
    container_name: ${APPLICATION}16_apachephp
    ports:
      - "81:80"
      - "444:443"
    links:
      - mysql
    volumes:
      - ${HOST_PS16_PATH}:/var/www/html:cached
      - ${PLUGIN_PATH}/:/var/www/html/modules/${PLUGIN_NAME}/
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    container_name: ${APPLICATION}_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DOCKER_DATA_FOLDER}/mysql57:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APPLICATION}_phpmyadmin
    links:
      - mysql
    ports:
      - 82:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge